### ISSUE TITLE
Unhandled Exception Loop on New Project/Solution Create

### ISSUE THREAD

**Issue by wibblemonkey** [adigostin/felix#18]
Extension causes VS to go into a loop of unhandled exceptions when a new Felix project is created.

C:\_felix2\FelixPackage\FelixProject.cpp(831)\FelixPackage.dll!00007FFCA9042C30: (caller: 00007FFC375D0B22) ReturnHr(1) tid(9348) 80070057 The parameter is incorrect.
    [Z80Project::GetGuidProperty]
C:\_felix2\FelixPackage\FelixProject.cpp(1509)\FelixPackage.dll!00007FFCA9042E06: (caller: 00007FFC374968F8) ReturnHr(2) tid(9348) 80070057 The parameter is incorrect.
    [Z80Project::GetMkDocument]
C:\_felix2\FelixPackage\FelixProject.cpp(831)\FelixPackage.dll!00007FFCA9042C30: (caller: 00007FFC375D0B22) ReturnHr(3) tid(9348) 80070057 The parameter is incorrect.
    [Z80Project::GetGuidProperty]
C:\_felix2\FelixPackage\FelixProject.cpp(1509)\FelixPackage.dll!00007FFCA9042E06: (caller: 00007FFC374968F8) ReturnHr(4) tid(9348) 80070057 The parameter is incorrect.
    [Z80Project::GetMkDocument]

This continues until the `devenv.exe` process has to be terminated externally.

-----

Microsoft Visual Studio Community 2022
Version 17.11.1
VisualStudio.17.Release/17.11.1+35219.272
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA335
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.11.230.51983
ASP.NET and Web Tools

AvaloniaPackage Extension   1.0
AvaloniaPackage Visual Studio Extension Detailed Info

Azure App Service Tools v3.0.0   17.11.230.51983
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.11.230.51983
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.11.0-3.24376.4+5e3a11e2e7f952da93f9d35bd63a2fa181c0608b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Felix   0.9.5
A project system, debug engine and simulator for the ZX Spectrum computer.

GhostDoc   24.1.24160.0
Generate XML Comments from your code, maintain clean and up-to-date documentation, produce help documentation in multiple formats, use intelligent source code Spell Checker in Visual Studio.

GitHub Copilot   0.2.1634.3922
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.60329.1 Commit Hash:15fce86a17f9f33e5bd7ca7ccb9b216aff149252
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.11.3.2436904+f07c7bb8e623ebcc1e1028cf11d101f866c77a79
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.11.38.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30715.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.11.0-3.24376.4+5e3a11e2e7f952da93f9d35bd63a2fa181c0608b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.11.0-beta.24317.3+c07c8ebad62f6629b36349381991a299598a8d74
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

WiX Toolset Visual Studio Extension   1.0.0.22
WiX Toolset Visual Studio Extension version 1.0.0.22
Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by adigostin** [comment]
I just released 0.9.6.
I couldn't reproduce your exact scenario (error dialog shown in infinite loop when creating project).
BUT: I fixed some pieces of code that were causing the same infinite loops in other scenarios. Hopefully your problem is fixed now too. I also improved the diagnostic data that gets sent to Sentry (error reporting server) from that error dialog; if this happens again, the new report should give me a good idea what's going on on your side.
If you try out 0.9.6 and see the same as in 0.9.5, please reopen this ticket.
